version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: kiranaflow_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kiranaflow_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://singh385536_db_user:YfaCGRe9X3h9SDga@cluster0.sgaajom.mongodb.net/
      - CLIENT_URL=http://localhost:5173
      - JWT_SECRET=GHGHGVYUYVYUIYBINYUIBYUYBUNUBH
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kiranaflow_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: