export const PRODUCT_SEARCH_SYNONYMS = {
  chawal: ['rice'],
  rice: ['chawal'],
  fal: ['fruit'],
  phal: ['fruit'],
  fruit: ['fal', 'phal'],
  sabzi: ['vegetable'],
  sabji: ['vegetable'],
  vegetable: ['sabzi', 'sabji'],
  doodh: ['milk'],
  milk: ['doodh'],
  aloo: ['potato'],
  potato: ['aloo'],
  pyaz: ['onion'],
  pyaaz: ['onion'],
  onion: ['pyaz', 'pyaaz'],
  tamatar: ['tomato'],
  tomato: ['tamatar'],
  haldi: ['turmeric'],
  turmeric: ['haldi'],
  jeera: ['cumin'],
  cumin: ['jeera'],
  dahi: ['curd', 'yogurt'],
  curd: ['dahi'],
  yogurt: ['dahi'],
  cheeni: ['sugar'],
  chini: ['sugar'],
  sugar: ['cheeni', 'chini'],
  tel: ['oil'],
  oil: ['tel'],
  namak: ['salt'],
  salt: ['namak'],
  anda: ['egg'],
  egg: ['anda'],
  aata: ['atta', 'flour'],
  atta: ['aata', 'flour'],
  flour: ['atta', 'aata'],
  dal: ['lentil'],
  lentil: ['dal'],
  makhan: ['butter'],
  butter: ['makhan'],
  chai: ['tea'],
  tea: ['chai'],
  coffee: ['kaapi'],
  kaapi: ['coffee']
};
